// This is an autogenerated file from Firebase Studio.

import { initializeApp, getApp, getApps } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyB7TqHAlkkURVLOVvy3Ccnp8nh4ObuFDgE",
  authDomain: "expense-tracker-867e8.firebaseapp.com",
  projectId: "expense-tracker-867e8",
  storageBucket: "expense-tracker-867e8.firebasestorage.app",
  messagingSenderId: "401634444791",
  appId: "1:401634444791:web:2bec2e9b9d3d34388fdaf2"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

const auth = getAuth(app);
const db = getFirestore(app);

export { app, auth, db };
